### ISSUE TITLE
Is this still in active development?

### ISSUE THREAD

**Issue by erick-thompson** [OctopusDeploy/terraform-provider-octopusdeploy#64]
I would love to be able to include Octopus in our terraform based configurations. Right now Octopus is one of the places where we need to perform manual steps to complete configuration.

My concern is that there haven't been any commits for a few months. Is this provider still under active development? I'm ok with either answer, I just don't want to spend time working with it if it isn't going to achieve maturity.

**Comment by droyad** [comment]
@erick-thompson It is and we do use it internally. At the moment I'm looking at code-generating parts to make the maintenance and upkeep easier.

**Comment by lukebailey** [comment]
Following up on this to see if the repo is still under active development (last commit November 2019)?

**Comment by ccamburn** [comment]
Also curious, as I'd like to start using it sooner rather than later. It was also previously on the Octopus Roadmap, and I don't see it there anymore.

Given there's been an RFC out since 2017, it would be nice to start managing all changes to projects in source control: https://octopusdeploy.uservoice.com/forums/170787-general/suggestions/15698781-version-control-configuration

**Comment by michaelpearce-gain** [comment]
Same, is there any update here at all for customers?

**Comment by robpearson** [comment]
Hi everyone, I'll share a quick update here but I'm planning to email everyone who has registered for updates via our roadmap soon. 

`tl;dr` This project is active but it's development is sporadic due to other priorities. We still aim to complete it and get it to a 1.0 milestone. 

We removed it from our public roadmap because we hadn't updated it recently but we use the provider internally to create whole Octopus instances from a template, including projects and processes. It is still in alpha because it is missing a few resources and we expect the shape of the current resources to change.

We’ve also started work on Config as Code, or git integration, with Octopus to achieve a complementary goal. Teams will be able to turn on Git integration per project, and Octopus will store the deployment process to the Git repository configured for the project. You can view and edit the deployment process with the process editor in the Octopus Web Portal, and when saved, Octopus will create a commit with the changes to the Git repository.

**Comment by ccamburn** [comment]
@robpearson Hey Rob, thanks for the update.

Correct me if I'm wrong, but all the git integration accomplishes is getting storage of configuration, correct? The main goal of configuration as code isn't just to "have" code, it's to be able to actually "run" said code. Will changes to the git propagate to the front-end? If not, it doesn't accomplish programmatic updates in source control.

**Comment by erick-thompson** [comment]
I like the idea of the git backed configuration, but that doesn't really help the scenarios I'm working towards.

The most immediate need for me is around Azure AKS. I have a set of terraform scripts that provisions and configures an AKS cluster. One of these steps outputs the certificate files needed for Octopus to deploy to the new cluster. Right now, I need to manually create the deployment target in Octopus. What I want to do is to have the deployment target be created (and deleted!) along with the AKS cluster itself. 

I guess, if the files stored in git are open for editing, that it could be done this way, but I'd be very hesitant to do so, as it feels too much like taking a dependency on an internal data structure.

**Comment by droyad** [comment]
> Right now, I need to manually create the deployment target in Octopus. What I want to do is to have the deployment target be created (and deleted!) along with the AKS cluster itself.

Yes, that is the scenario you would use this library for. Some kinds of deployment targets are already supported in this library (https://github.com/OctopusDeploy/terraform-provider-octopusdeploy/blob/master/octopusdeploy/resource_machine_test.go#L45)

**Comment by droyad** [comment]
> Will changes to the git propagate to the front-end?
Editing the project via the UI will be first-class projects stored in git. This includes edits made in the git stored file propagating to the UI.

**Comment by wjrogers** [comment]
Would like to chime in to say I'd personally much prefer to use Terraform to configure Octopus Deploy. Terraform's ability to preview changes lets you know exactly what you're going to get when you apply, taking some of the guesswork out of automation -- and easing some of the trial and error. 

TeamCity has per-project version-controlled settings like Octopus Deploy is proposing. I tried it, and I didn't like it at all. Making changes in a UI that get auto-committed to a git repository is just a bad experience. Experimenting leads to a series of junk commits in the repository, diluting the value of change history. That makes me reluctant to change anything, which undermines the goal of keeping the UI usable. (TeamCity's implementation is further complicated by using a DSL with its own development dependencies.)

Octopus Deploy is the only part of the infrastructure I manage that isn't configured by Terraform. Clicking around in the UI feels like banging rocks together in comparison. I'd love to close the gap.

**Comment by droyad** [comment]
@wjrogers I agree with you on the Terraform and TeamCity sentiments.

Our Configuration as Code feature will be much more like GitHub Actions or Azure DevOps except it also has a first class UI.

Only the Deployment process, Variables and some project settings will be stored in git. It's also opt in.

Seeing the REST API will keep working for these, I don't see why this library couldn't keep supporting processes and variables.

**Comment by AdminTurnedDevOps** [comment]
Hey all. We're back to actively working on the Terraform provider. In fact, we're closing in on a beta. Once we're ready to release, it'll be in the Octopus Deploy newsletter, slack community, and social media.
